import { useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { ArrowRight, ArrowUpRight, Bell, CalendarDays, Camera, Check, CheckCheck, ChevronRight, CircleHelp, Download, Droplets, Leaf, MapPin, Menu, Package, Plus, Settings, ShieldCheck, ShoppingBasket, Sprout, Tractor, Upload, Wallet, Wheat, X, LayoutDashboard, Pencil, Trash2, CloudSun, Wrench, LogOut } from 'lucide-react';
import { AddButton, Button, Card, Empty, Heading, Input, LinkButton, Modal, Note, Stat, dateLabel, money, number } from './components/UI';
import { RecordForm, type EditRecord, type FormKind } from './components/RecordForm';
import { initialState, today, uid, useFarm } from './store';
import { budgetTotals, deliveredCost, fertiliserNeed, germination, irrigationNeed, serviceState } from './domain.mjs';
import type { FarmState, Page, Soil } from './types';
import { SoilPage } from './pages/SoilPage';
import { SettingsPage } from './pages/SettingsPage';
import { ResourcesPage } from './pages/ResourcesPage';

const pages = [
  {id:'home',label:'Overview',icon:LayoutDashboard,description:'Your farm at a glance'},
  {id:'planning',label:'Planning',icon:CalendarDays,description:'Crops & planting schedules'},
  {id:'finance',label:'Financial Plan',icon:Wallet,description:'Budgets & expenses'},
  {id:'resources',label:'Resources',icon:Package,description:'Land, stock & irrigation'},
  {id:'soil',label:'Soil & Seed Check',icon:Leaf,description:'Observations & test records'},
  {id:'equipment',label:'Equipment Care',icon:Tractor,description:'Maintenance & service history'},
  {id:'buying',label:'Buy Together',icon:ShoppingBasket,description:'Quotes & group purchases'},
  {id:'alerts',label:'Notifications',icon:Bell,description:'Seasonal & farm reminders'},
] as const;
function fromHash():Page {const p=location.hash.slice(1);return [...pages.map(p=>p.id),'settings'].includes(p)?p as Page:'home';}
export default function App() {
  const {state,update,problem}=useFarm();
  const [page,setPage]=useState<Page>(fromHash);
  const [menu,setMenu]=useState(false);
  const [form,setForm]=useState<{kind:FormKind;record?:EditRecord}|null>(null);
  const [toast,setToast]=useState('');
  const [confirm,setConfirm]=useState<{text:string;action:()=>void}|null>(null);
  const [capabilities,setCapabilities]=useState({online:false,soilAI:false});
  const [loadingWeather,setLoadingWeather]=useState(false);
  const [weatherError,setWeatherError]=useState('');
  const weatherRequest=useRef(false);
  const [clockTick,setClockTick]=useState(0);
  const seasonKey=JSON.stringify([state.profile.latitude,state.profile.longitude,state.profile.seasonStart,state.profile.seasonEnd]);
  useEffect(()=>{const timer=setInterval(()=>setClockTick(t=>t+1),60_000);return()=>clearInterval(timer);},[]);
  useEffect(()=>{if(capabilities.online&&state.seasonalAuto&&!weatherRequest.current&&(state.seasonalCheck?.key!==seasonKey||Date.now()-(state.seasonalCheck?.at||0)>86400000))void refreshOutlook();},[capabilities.online,state.seasonalAuto,seasonKey,clockTick]);
  const drawer=useRef<HTMLDialogElement>(null);
  const menuButton=useRef<HTMLButtonElement>(null);
  useEffect(()=>{const handler=()=>setPage(fromHash());window.addEventListener('hashchange',handler);return()=>window.removeEventListener('hashchange',handler);},[]);
  useEffect(()=>{fetch('/api/status').then(r=>r.ok?r.json():Promise.reject()).then(x=>setCapabilities({online:true,soilAI:x.soilAI})).catch(()=>setCapabilities({online:false,soilAI:false}));},[]);
  useEffect(()=>{if(menu)drawer.current?.showModal();else drawer.current?.close();},[menu]);
  useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(t);},[toast]);
  function navigate(p:Page) {location.hash=p;setPage(p);setMenu(false);window.scrollTo({top:0});}
  function save(next:FarmState){const ok=update(next);if(ok)setToast('Saved to this device');return ok;}
  const open=(kind:FormKind,record?:EditRecord)=>setForm({kind,record});
  function remove(collection:'fields'|'costs'|'stock'|'equipment'|'quotes'|'groups',id:string) {
    setConfirm({text:'Remove this record? Export a backup first if you need a copy. Historical service and soil records are kept.',action:()=>{
      const next=structuredClone(state);(next[collection] as {id:string}[])=(next[collection] as {id:string}[]).filter(x=>x.id!==id);
      if(collection==='fields')next.tasks=next.tasks.filter(x=>x.fieldId!==id);save(next);
    }});
  }
  const totals=budgetTotals(state.profile.budget,state.costs);
  const upcoming=state.tasks.filter(t=>!t.done).sort((a,b)=>a.date.localeCompare(b.date));
  const farmAlerts=[
    ...upcoming.filter(t=>t.date<=new Date(Date.now()+7*86400000).toLocaleDateString('en-CA',{timeZone:'Africa/Johannesburg'})).map(t=>({id:`task:${t.id}:${t.date}`,title:t.name,body:`${state.fields.find(f=>f.id===t.fieldId)?.name||'Field'} · ${dateLabel(t.date)}`,page:'planning' as Page,kind:'Task'})),
    ...state.equipment.filter(e=>serviceState(e,today()).status!=='Up to date').map(e=>({id:`service:${e.id}:${e.nextHours}:${e.dueDate}`,title:`${e.name}: ${serviceState(e,today()).status.toLowerCase()}`,body:'Review the service schedule before the next job.',page:'equipment' as Page,kind:'Maintenance'})),
    ...state.stock.filter(s=>s.quantity<=s.reorder).map(s=>({id:`stock:${s.id}:${s.quantity}`,title:`${s.name} is running low`,body:`${number(s.quantity)} ${s.unit} remaining. Check your needs before buying.`,page:'resources' as Page,kind:'Stock'})),
    ...state.outlooks.map(o=>({id:o.id,title:'Your seasonal outlook is ready',body:`${dateLabel(o.from)} – ${dateLabel(o.to)} · ${o.location}`,page:'alerts' as Page,kind:'Seasonal'})),
  ];
  const unread=farmAlerts.filter(a=>!state.readAlerts.includes(a.id)).length;
  const navigation=(mobile=false)=><><a className="brand" href="#home" onClick={()=>navigate('home')}><Sprout size={32}/><span>FarmWise<span className="brand-dot">.</span></span></a><div className="nav-caption">YOUR FARM WORKSPACE</div><nav aria-label={mobile?'Mobile navigation':'Main navigation'}>{pages.map(p=><a key={p.id} href={'#'+p.id} aria-current={page===p.id?'page':undefined} onClick={()=>navigate(p.id)} className={'nav-item '+(page===p.id?'active':'')}><p.icon size={20}/><span>{p.label}</span>{p.id==='alerts'&&unread>0&&<span className="count">{unread}</span>}</a>)}</nav><div className="sidebar-bottom"><button className="nav-item" onClick={()=>navigate('settings')}><Settings size={19}/>Farm settings</button><div className="profile"><span className="avatar">{state.profile.name.slice(0,1)}</span><div><strong>{state.profile.name}</strong><small>{state.profile.location}</small></div></div></div></>;
  const rowTools=(kind:FormKind,record:EditRecord,collection:Parameters<typeof remove>[0])=><div className="row-tools"><button className="icon-button" aria-label={`Edit ${'name' in record?record.name:'record'}`} onClick={()=>open(kind,record)}><Pencil size={15}/></button><button className="icon-button" aria-label={`Remove ${'name' in record?record.name:'record'}`} onClick={()=>remove(collection,record.id)}><Trash2 size={15}/></button></div>;
  async function refreshOutlook(){if(weatherRequest.current)return;weatherRequest.current=true;update(current=>({...current,seasonalCheck:{key:seasonKey,at:Date.now()}}));setLoadingWeather(true);setWeatherError('');try {
    const p=state.profile;const response=await fetch('/api/seasonal',{method:'POST',headers:{'Content-Type':'application/json','X-FarmWise-Client':'web'},body:JSON.stringify({latitude:p.latitude,longitude:p.longitude,start:p.seasonStart,end:p.seasonEnd})});const body=await response.json();if(!response.ok)throw new Error(body.error||'Could not load seasonal data.');
    const outlook={...body,id:uid(),created:new Date().toISOString(),location:p.location};update(current=>({...current,outlooks:[outlook,...current.outlooks].slice(0,6)}));
  }catch(e){setWeatherError((e as Error).message||'Weather service unavailable. Your saved farm records are unaffected.');}finally{weatherRequest.current=false;setLoadingWeather(false);}}
  return <div className="app-shell"><a href="#main-content" className="skip-link" onClick={e=>{e.preventDefault();document.getElementById("main-content")?.focus();}}>Skip to content</a><aside className="sidebar">{navigation()}</aside>
    <dialog ref={drawer} aria-label="Farm navigation" className="mobile-drawer" onCancel={e=>{e.preventDefault();setMenu(false);menuButton.current?.focus();}} onClick={e=>{if(e.target===e.currentTarget)setMenu(false);}}><button className="icon-button drawer-close" aria-label="Close navigation" onClick={()=>{setMenu(false);menuButton.current?.focus();}}><X/></button>{navigation(true)}</dialog>
    <div className="workspace"><header className="topbar"><div className="breadcrumb"><button ref={menuButton} className="icon-button menu-toggle" aria-label="Open navigation" aria-expanded={menu} onClick={()=>setMenu(true)}><Menu/></button><span>{state.profile.farm}</span><ChevronRight size={14}/><strong>{pages.find(p=>p.id===page)?.label||'Settings'}</strong></div><div className="topbar-right"><span className="season-label"><span className="status-dot"/>{state.profile.season}</span><button className="notification-button icon-button" aria-label={`Notifications, ${unread} unread`} onClick={()=>navigate('alerts')}><Bell size={21}/>{unread>0&&<i>{unread}</i>}</button><button className="avatar" onClick={()=>navigate('settings')} aria-label="Farm settings">{state.profile.name.slice(0,1)}</button></div></header>
      <main id="main-content" tabIndex={-1}>
        {state.demo&&<div className="demo-banner"><span><Sprout size={15}/>You’re exploring an example farm. All figures are illustrative.</span><button onClick={()=>navigate('settings')}>Set up my farm <ArrowRight size={14}/></button></div>}
        {problem&&<p role="alert" className="form-error">{problem}</p>}
        {page==='home'&&<>
          <Heading eyebrow="A LITTLE PLANNING. A BETTER SEASON." title={`Welcome back, ${state.profile.name}.`} description="A clear view of your farm. A good place to start." action={<AddButton onClick={()=>open('field')}>New crop plan</AddButton>}/>
          <section className="farm-hero"><div><span className="hero-kicker"><MapPin size={15}/>{state.profile.location}</span><h2>Make every<br/><em>input count.</em></h2><p>Plan with purpose, keep track of your resources,<br className="desktop-only"/> and give your next season a strong start.</p><button className="hero-link" onClick={()=>navigate('planning')}>Open my seasonal plan <ArrowUpRight size={18}/></button></div><div className="hero-field"><Wheat size={116} strokeWidth={0.8}/><div><span>YOUR LAND</span><strong>{number(state.profile.land)} <small>hectares</small></strong><p>{state.fields.length} field{state.fields.length===1?'':'s'} in your workspace</p></div></div></section>
          <div className="stats-grid"><Stat label="Land planned" value={`${number(state.fields.reduce((s,f)=>s+f.area,0))} ha`} detail={`of ${number(state.profile.land)} ha available`}/><Stat label="Season budget" value={money(state.profile.budget)} detail={`${money(totals.planned)} planned`}/><Stat label="Budget remaining" value={money(totals.remaining)} detail={`${money(totals.spent)} actually spent`}/><Stat label="Upcoming tasks" value={upcoming.length.toString().padStart(2,'0')} detail="Your saved planting schedule"/></div>
          <div className="two-columns"><Card title="Your next steps" action={<LinkButton onClick={()=>navigate('alerts')}>View all</LinkButton>}>{farmAlerts.length?farmAlerts.slice(0,4).map(a=><button className="action-row" key={a.id} onClick={()=>navigate(a.page)}><span className="icon-tile">{a.kind==='Maintenance'?<Wrench/>:a.kind==='Stock'?<Package/>:<CalendarDays/>}</span><span><strong>{a.title}</strong><small>{a.body}</small></span><ChevronRight size={18}/></button>):<Empty title="A little breathing room" body="No tasks or maintenance reminders are due. Add your plans to get started."/>}</Card><Card title="This season" action={<LinkButton onClick={()=>navigate('planning')}>Manage fields</LinkButton>}>{state.fields.length?state.fields.map(f=><button className="field-row" key={f.id} onClick={()=>navigate('planning')}><span className="crop-tile"><Wheat size={30}/></span><span><strong>{f.crop}</strong><small>{f.name} · {number(f.area)} ha</small></span><span className={'pill '+(f.status==='Growing'?'green':'')}>{f.status}</span></button>):<Empty title="Your first field starts here" body="Add a crop plan to connect your budget, resources, and tasks." action={<Button onClick={()=>open('field')}>Add a field</Button>}/>}<div className="quiet-tip"><Leaf size={18}/><p>Keep your field records together. Small decisions are easier when you can see the whole picture.</p></div></Card></div>
        </>}
        {page==='planning'&&<><Heading eyebrow="PLAN THE SEASON" title="Good seasons start here." description="Your fields, crops, and planting schedule in one place." action={<AddButton onClick={()=>open('field')}>Add crop plan</AddButton>}/><div className="section-heading"><h2>{state.profile.season}</h2><span className="muted">{dateLabel(state.profile.seasonStart)} – {dateLabel(state.profile.seasonEnd)}</span></div><div className="field-grid">{state.fields.map(f=><Card key={f.id}><div className="field-card-top"><span className="crop-tile"><Wheat size={32}/></span>{rowTools('field',f,'fields')}</div><div className="section-heading"><h2>{f.name}</h2><span className="pill">{f.status}</span></div><p className="crop-name">{f.crop} <span>· {number(f.area)} ha</span></p><dl className="details"><div><dt>Variety</dt><dd>{f.variety||'Not set'}</dd></div><div><dt>Planting date</dt><dd>{dateLabel(f.planted)}</dd></div><div><dt>Expected harvest</dt><dd>{dateLabel(f.harvest)}</dd></div><div><dt>Seed estimate</dt><dd>{number(f.area*f.seedRate)} {f.seedUnit==='kg/ha'?'kg':'seeds'}</dd></div></dl><small className="muted">From your entered rate of {number(f.seedRate)} {f.seedUnit}.</small></Card>)}</div>{!state.fields.length&&<Card><Empty title="Plan your first field" body="Choose a crop, enter your field area, and set your dates." action={<Button onClick={()=>open('field')}>Add crop plan</Button>}/></Card>}<Card title="Planting schedule" action={<Button secondary onClick={()=>open('task')} disabled={!state.fields.length}><Plus size={16}/>Add task</Button>}>{state.tasks.length?state.tasks.slice().sort((a,b)=>a.date.localeCompare(b.date)).map(t=><div className={'task-row '+(t.done?'done':'')} key={t.id}><input type="checkbox" checked={t.done} aria-label={`Complete ${t.name}`} onChange={()=>save({...state,tasks:state.tasks.map(x=>x.id===t.id?{...x,done:!x.done}:x)})}/><div><strong>{t.name}</strong><small>{state.fields.find(f=>f.id===t.fieldId)?.name}</small></div><span className={t.date<today()&&!t.done?'overdue':''}>{dateLabel(t.date)}</span><button className="icon-button" aria-label={`Delete task ${t.name}`} onClick={()=>setConfirm({text:'Remove this planting task?',action:()=>{save({...state,tasks:state.tasks.filter(x=>x.id!==t.id)});}})}><Trash2 size={15}/></button></div>):<p className="muted">Add tasks for soil preparation, planting, and crop checks.</p>}</Card></>}
        {page==='finance'&&<><Heading eyebrow="KNOW WHERE YOUR MONEY GOES" title="Your season, in numbers." description="Keep your plans and actual spending side by side." action={<AddButton onClick={()=>open('cost')}>Add budget item</AddButton>}/><div className="stats-grid"><Stat label="Season budget" value={money(state.profile.budget)} detail="Set in farm settings"/><Stat label="Planned costs" value={money(totals.planned)} detail={`${money(totals.unallocated)} unallocated`}/><Stat label="Actual spending" value={money(totals.spent)} detail="Recorded expenses"/><Stat label="Remaining" value={money(totals.remaining)} detail={totals.remaining<0?'You are over budget':'Budget less actual spending'}/></div><Card title="Budget overview" action={<LinkButton onClick={()=>navigate('settings')}>Edit budget</LinkButton>}><div className="budget-meter"><span>{state.profile.budget?Math.round(totals.spent/state.profile.budget*100):0}% spent</span><span>{money(totals.spent)} / {money(state.profile.budget)}</span></div><progress max={Math.max(state.profile.budget,1)} value={Math.min(totals.spent,state.profile.budget)}/>{totals.unallocated<0&&<p className="overdue">Your planned costs exceed the budget by {money(-totals.unallocated)}.</p>}</Card><Card title="Budget & expenses">{state.costs.length?<div className="table-wrap"><table><thead><tr><th>Item</th><th>Field</th><th>Planned</th><th>Spent</th><th>Difference</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{state.costs.map(c=><tr key={c.id}><td><strong>{c.name}</strong><small>{c.category} · {dateLabel(c.date)}</small></td><td>{state.fields.find(f=>f.id===c.fieldId)?.name||(c.fieldId?'Archived field':'Whole farm')}</td><td>{money(c.planned)}</td><td>{money(c.actual)}</td><td className={c.actual>c.planned?'overdue':''}>{money(c.planned-c.actual)}</td><td>{rowTools('cost',c,'costs')}</td></tr>)}</tbody></table></div>:<Empty title="Give every rand a plan" body="Record planned costs first, then update actual spending as you buy."/>}</Card><Note>Cost differences are budget comparisons, not verified savings. Track harvest yield as well before judging a season’s performance.</Note></>}
        {page==='resources'&&<ResourcesPage state={state} onAdd={()=>open('stock')} tools={s=>rowTools('stock',s,'stock')}/>}
        {page==='soil'&&<SoilPage state={state} save={save} aiEnabled={capabilities.soilAI} addSeed={()=>open('seed')}/>}
        {page==='equipment'&&<><Heading eyebrow="READY FOR THE NEXT JOB" title="Look after what works." description="Service reminders and a record of every repair." action={<AddButton onClick={()=>open('equipment')}>Add equipment</AddButton>}/><div className="field-grid">{state.equipment.map(e=>{const status=serviceState(e,today());return <Card key={e.id}><div className="field-card-top"><span className="crop-tile"><Tractor size={32}/></span>{rowTools('equipment',e,'equipment')}</div><div className="section-heading"><h2>{e.name}</h2><span className={'pill '+(status.status==='Due now'?'clay':'')}>{status.status}</span></div><dl className="details"><div><dt>Current hours</dt><dd>{number(e.hours)} h</dd></div><div><dt>Next service</dt><dd>{e.nextHours==null?'Date-based':`${number(e.nextHours)} h`}</dd></div><div><dt>Inspection date</dt><dd>{dateLabel(e.dueDate)}</dd></div></dl>{status.hoursLeft!=null&&<p className="service-remaining">{status.hoursLeft<=0?`${number(Math.abs(status.hoursLeft))} hours past service threshold`:`${number(status.hoursLeft)} operating hours remaining`}</p>}<p className="muted small">{e.notes}</p><Button secondary onClick={()=>open('service',e)}><Wrench size={16}/>Log maintenance</Button></Card>;})}</div>{!state.equipment.length&&<Card><Empty title="Keep equipment ready" body="Add equipment and the manufacturer’s service schedule to get reminders."/></Card>}<Card title="Service history">{state.services.length?state.services.map(s=><div className="action-row" key={s.id}><span className="icon-tile"><CheckCheck/></span><span><strong>{s.name}</strong><small>{dateLabel(s.date)} · {number(s.hours)} h · {s.notes}</small></span><strong>{money(s.cost)}</strong></div>):<p className="muted">Completed maintenance will appear here. Service costs also go into your financial plan.</p>}</Card></>}
        {page==='buying'&&<><Heading eyebrow="BUY WITH A CLEAR PICTURE" title="Better buying starts here." description="Compare the full cost and keep group purchases organised." action={<AddButton onClick={()=>open('quote')}>Add supplier quote</AddButton>}/><Note>These are your saved quotes and coordination records. FarmWise does not place orders or take payments. Confirm stock, delivery, and terms with the supplier.</Note><Card title="Supplier quotes"><p className="muted small">Compare the same variety, formulation, pack size, and required quantity. Totals include delivery.</p>{state.quotes.length?<div className="table-wrap"><table><thead><tr><th>Supplier / product</th><th>Unit price</th><th>Quantity</th><th>Delivery</th><th>Total</th><th>Expiry</th><th/></tr></thead><tbody>{state.quotes.slice().sort((a,b)=>deliveredCost(a.price,a.quantity,a.delivery)-deliveredCost(b.price,b.quantity,b.delivery)).map(q=><tr key={q.id}><td><strong>{q.supplier}</strong><small>{q.product} · {q.spec}</small></td><td>{money(q.price)}<small>per {q.unit}</small></td><td>{q.quantity}</td><td>{money(q.delivery)}</td><td><strong>{money(deliveredCost(q.price,q.quantity,q.delivery))}</strong></td><td className={q.expires<today()?'overdue':''}>{dateLabel(q.expires)}</td><td>{rowTools('quote',q,'quotes')}</td></tr>)}</tbody></table></div>:<Empty title="Compare before you commit" body="Add quotes from local suppliers to see product and delivery costs together."/>}</Card><Card title="Group purchases" action={<Button secondary onClick={()=>open('group')}><Plus size={16}/>New group record</Button>}>{state.groups.length?<div className="group-grid">{state.groups.map(g=><section className="group-card" key={g.id}><div className="section-heading"><h3>{g.name}</h3>{rowTools('group',g,'groups')}</div><p>{g.product}</p><span className="pill">{g.status}</span><div className="budget-meter"><span>{g.pledged} / {g.target} {g.unit}</span><span>Your share: {g.mine}</span></div><progress max={g.target} value={Math.min(g.pledged,g.target)}/><small>Deadline {dateLabel(g.deadline)}</small></section>)}</div>:<Empty title="There’s strength in buying together" body="Record a shared target, your quantity, and supplier confirmation with your cooperative."/>}</Card></>}
        {page==='alerts'&&<><Heading eyebrow="THE RIGHT NUDGE AT THE RIGHT TIME" title="Stay a step ahead." description="Seasonal outlooks, planting tasks, and equipment reminders." action={<Button secondary onClick={()=>save({...state,readAlerts:farmAlerts.map(a=>a.id)})}><CheckCheck size={17}/>Mark all read</Button>}/><Card title="Seasonal outlook" action={<Button onClick={refreshOutlook} disabled={loadingWeather||!capabilities.online}><CloudSun size={17}/>{loadingWeather?'Checking season…':'Check my season'}</Button>}><p>Receive a regional summary for <strong>{state.profile.season}</strong> in {state.profile.location}. No daily or weekly weather dashboard.</p><p className="muted small">{dateLabel(state.profile.seasonStart)} – {dateLabel(state.profile.seasonEnd)} · Change location and dates in Settings.</p>{!capabilities.online&&<Note>Start the app with npm run dev from the repository root to connect seasonal and AI services.</Note>}{weatherError&&<p role="alert" className="form-error">{weatherError}</p>}{state.outlooks.slice(0,1).map(o=><div className="seasonal-card" key={o.id}><span className="pill">Regional outlook</span><h3>Review your seasonal water plan</h3><p>The model’s average temperature is {o.temperature}°C, with {o.rainfall} mm total rainfall across {o.days} available days. Compare this with your crop plan and actual field conditions.</p><p className="muted small">{dateLabel(o.from)} – {dateLabel(o.to)}{o.partial?' · Partial season coverage':''} · Retrieved {new Date(o.created).toLocaleString('en-ZA')}</p><a href="https://open-meteo.com/en/docs/seasonal-forecast-api" target="_blank" rel="noreferrer">Source: Open-Meteo / ECMWF</a></div>)}<Note>Seasonal models describe a broad area and uncertainty remains high. This app does not infer “wetter than normal”, crop suitability, or planting dates without a validated baseline and local guidance.</Note></Card><Card title={`Farm reminders (${farmAlerts.length})`}>{farmAlerts.length?farmAlerts.map(a=><div className={'action-row alert-row '+(!state.readAlerts.includes(a.id)?'unread':'')} key={a.id}><span className="icon-tile"><Bell size={20}/></span><div><span className="eyebrow">{a.kind}</span><strong>{a.title}</strong><small>{a.body}</small></div><button className="text-button" onClick={()=>{save({...state,readAlerts:[...state.readAlerts,a.id]});navigate(a.page);}}>Review<ChevronRight size={17}/></button></div>):<Empty title="You’re all caught up" body="Reminders appear when your saved tasks, stock, or equipment need attention."/>}</Card><Note>Reminders are checked while the app is open. Background push, SMS, and WhatsApp delivery need a hosted notification service and are not enabled in this local version.</Note></>}
        {page==='settings'&&<SettingsPage state={state} save={save} online={capabilities.online} ai={capabilities.soilAI} confirm={(text,action)=>setConfirm({text,action})}/>}
        <footer className="page-footer"><span><Sprout size={15}/> FarmWise · Grow with a plan.</span><span>Saved on this device · Export a backup in Settings</span></footer>
      </main>
    </div>
    {toast&&<div role="status" className="toast"><Check size={17}/>{toast}</div>}
    {form&&<RecordForm kind={form.kind} record={form.record} state={state} onSave={save} onClose={()=>setForm(null)}/>}
    {confirm&&<Modal title="Please confirm" onClose={()=>setConfirm(null)}><p>{confirm.text}</p><div className="modal-actions"><Button secondary onClick={()=>setConfirm(null)}>Cancel</Button><Button onClick={()=>{confirm.action();setConfirm(null);}}>Confirm</Button></div></Modal>}
  </div>;
}



